Mobile menu branch
riskmaris/mobile-menu-branch pull request #9
Opened 2023-04-18 13:49 UTC by riskmaris

- Added JavaScript linters
- Added more styling
- Updated HTML file.

2023-04-18 15:28 UTC, GzimAsani requested changes
### Hello, @riskmaris                    :wave:   
 Good job so far,  done There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Good job with the hamburger button, it works good :+1: 

 ## Required Changes 

- [ ] Check the comments below :arrow_double_down: 

 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers, and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._



# NOTE: I approved this MR by mistake so the approval will be reverted soon.

2023-04-18 15:28 UTC, GzimAsani commented on index.html
> +            <ul class="popup-list">
- [ ] When the user clicks those options it should move to the correct part of the application, currently your app doesn't do that
https://www.awesomescreenshot.com/video/16626532?key=ed0d29cc9ef9c88242dfc9c6f8d63d30
- [ ] Also remember that after clicking the option and the app sending you to the correct part of the app, the popup should close

2023-04-18 15:28 UTC, GzimAsani commented on index.html
> +              <li><a href="#contact">Contact</a></li>
- [ ] Please adjust the margin/paddings between the options in order to match the design better, also adjust the X with the height and width from the design
Design:
![image](https://user-images.githubusercontent.com/62705947/232824408-907dbdce-597d-47e5-8b6f-147c5fce5abb.png)
Yours:
![image](https://user-images.githubusercontent.com/62705947/232824561-796ea83e-93b3-4914-84de-5b1aa9cd41f6.png)

2023-04-18 17:12 UTC, merged

2023-04-18 18:50 UTC, enniopo commented
@riskmaris the dashboard has been updated and you can now request another code review request once you are ready. 
Thank you and apologies for the inconvenience.

2023-04-18 18:53 UTC, GzimAsani commented
Hi @riskmaris, I am glad that your dashboard has been updated. I sincerely apologise for this inconvenience

2023-04-19 07:58 UTC, riskmaris commented
Hi
I have made the necessary changes but the problem I have right now is that
I cant make another pull request because when you approved the first one, i
merged it. What should i do?

On Tue, 18 Apr 2023 at 21:53, Gzim Asani ***@***.***> wrote:

> Hi @riskmaris <https://github.com/riskmaris>, I am glad that your
> dashboard has been updated. I sincerely apologise for this inconvenience
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/riskmaris/mobile-menu-branch/pull/9#issuecomment-1513649400>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4Q6X7H25KP6TN4K6CJO7HLXB3PJXANCNFSM6AAAAAAXCVN2HQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-04-19 18:26 UTC, GzimAsani commented
> Hi I have made the necessary changes but the problem I have right now is that I cant make another pull request because when you approved the first one, i merged it. What should i do?
> […](#)

Hi @riskmaris, please ask for a code review on a new PR and mention this PR on a link so the new reviewer can see the required changes that I’ve made